//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Header:public drogon::DrTemplate<Header>
{
public:
	Header(){};
	virtual ~Header(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
