//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Index.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Index::genText(const DrTemplateData& Index_view_data)
{
	drogon::OStringStream Index_tmp_stream;
	std::string layoutName{"Layout.csp"};
	Index_tmp_stream << "<main class=\"px-3\">\n";
	Index_tmp_stream << "    <form action=\"/pdf/convertPdf\" method=\"post\" enctype=\"multipart/form-data\">\n";
	Index_tmp_stream << "    <div class=\"mb-3\">\n";
	Index_tmp_stream << "      <label for=\"formFile\" class=\"form-label\">请上传要转换pdf的文档</label>\n";
	Index_tmp_stream << "      <input class=\"form-control\" type=\"file\" id=\"file\" name=\"file\">\n";
	Index_tmp_stream << "      <button type=\"submit\" class=\"btn btn-dark\">转换</button>\n";
	Index_tmp_stream << "    </div>\n";
	Index_tmp_stream << "    </form>\n";
	Index_tmp_stream << "</main>\n";
if(layoutName.empty())
{
std::string ret{std::move(Index_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Index_view_data;
auto str = std::move(Index_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
