//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Header.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Header::genText(const DrTemplateData& Header_view_data)
{
	drogon::OStringStream Header_tmp_stream;
	std::string layoutName{""};
	Header_tmp_stream << "  <div class=\"container\">\n";
	Header_tmp_stream << "    <header class=\"d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom\">\n";
	Header_tmp_stream << "      <a href=\"/\" class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none\">\n";
	Header_tmp_stream << "        <svg class=\"bi me-2\" width=\"40\" height=\"32\"><use xlink:href=\"#bootstrap\"/></svg>\n";
	Header_tmp_stream << "        <span class=\"fs-4\">欢迎</span>\n";
	Header_tmp_stream << "      </a>\n";
	Header_tmp_stream << "      <ul class=\"nav nav-pills\">\n";
	Header_tmp_stream << "        <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">注销</a></li>\n";
	Header_tmp_stream << "      </ul>\n";
	Header_tmp_stream << "    </header>\n";
	Header_tmp_stream << "  </div>\n";
Header_tmp_stream<<"\n";
Header_tmp_stream<<"\n";
if(layoutName.empty())
{
std::string ret{std::move(Header_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Header_view_data;
auto str = std::move(Header_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
