//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Index.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Index::genText(const DrTemplateData& Index_view_data)
{
	drogon::OStringStream Index_tmp_stream;
	std::string layoutName{"Layout.csp"};
	Index_tmp_stream << "<main class=\"px-3\">\n";
	Index_tmp_stream << "    <h1>Cover your page.</h1>\n";
	Index_tmp_stream << "    <p class=\"lead\">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>\n";
	Index_tmp_stream << "    <p class=\"lead\">\n";
	Index_tmp_stream << "      <a href=\"#\" class=\"btn btn-lg btn-light fw-bold border-white bg-white\">Learn more</a>\n";
	Index_tmp_stream << "    </p>\n";
	Index_tmp_stream << "</main>\n";
if(layoutName.empty())
{
std::string ret{std::move(Index_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Index_view_data;
auto str = std::move(Index_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
