//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Layout:public drogon::DrTemplate<Layout>
{
public:
	Layout(){};
	virtual ~Layout(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
