//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Login.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Login::genText(const DrTemplateData& Login_view_data)
{
	drogon::OStringStream Login_tmp_stream;
	std::string layoutName{""};
	Login_tmp_stream << "<!DOCTYPE html>\n";
	Login_tmp_stream << "<html lang=\"zh-CN\">\n";
Login_tmp_stream<<"\n";
	Login_tmp_stream << "  <head>\n";
	Login_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	Login_tmp_stream << "    ";
{
    auto templ=DrTemplateBase::newTemplate("Base.csp");
    if(templ){
      Login_tmp_stream<< templ->genText(Login_view_data);
    }
}
Login_tmp_stream<<"\n";
	Login_tmp_stream << "      <title>Login Page</title>\n";
	Login_tmp_stream << "      <style>\n";
	Login_tmp_stream << "      .gradient-custom {\n";
	Login_tmp_stream << "      /* fallback for old browsers */\n";
	Login_tmp_stream << "      background: #6a11cb;\n";
Login_tmp_stream<<"\n";
	Login_tmp_stream << "      /* Chrome 10-25, Safari 5.1-6 */\n";
	Login_tmp_stream << "      background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));\n";
Login_tmp_stream<<"\n";
	Login_tmp_stream << "      /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n";
	Login_tmp_stream << "      background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))\n";
	Login_tmp_stream << "      }\n";
	Login_tmp_stream << "      </style>\n";
	Login_tmp_stream << "  </head>\n";
Login_tmp_stream<<"\n";
	Login_tmp_stream << "  <body>\n";
	Login_tmp_stream << "    <section class=\"vh-100 gradient-custom\">\n";
	Login_tmp_stream << "      <div class=\"container py-5 h-100\">\n";
	Login_tmp_stream << "        <div class=\"row d-flex justify-content-center align-items-center h-100\">\n";
	Login_tmp_stream << "          <div class=\"col-12 col-md-8 col-lg-6 col-xl-5\">\n";
	Login_tmp_stream << "            <div class=\"card bg-dark text-white\" style=\"border-radius: 1rem;\">\n";
	Login_tmp_stream << "              <div class=\"card-body p-5 text-center\">\n";
Login_tmp_stream<<"\n";
	Login_tmp_stream << "              <form action=\"/UserController/loginAuth\" method=\"post\">\n";
	Login_tmp_stream << "                <div class=\"mb-md-5 mt-md-4 pb-5\">\n";
	Login_tmp_stream << "                  <h2 class=\"fw-bold mb-2 text-uppercase\">登录</h2>\n";
	Login_tmp_stream << "                  <p class=\"text-white-50 mb-5\"></p>\n";
	Login_tmp_stream << "                  <div class=\"row mb-4\">\n";
	Login_tmp_stream << "                    <div class=\"col\">\n";
	Login_tmp_stream << "                      <div class=\"form-outline form-white\">\n";
	Login_tmp_stream << "                        <input type=\"text\" id=\"typeUsernameX\" name=\"username\" class=\"form-control form-control-lg\" />\n";
	Login_tmp_stream << "                        <label class=\"form-label text-start\" for=\"typeUsernameX\">账户</label>\n";
	Login_tmp_stream << "                      </div>\n";
	Login_tmp_stream << "                    </div>\n";
	Login_tmp_stream << "                  </div>\n";
	Login_tmp_stream << "                  <div class=\"row mb-4\">\n";
	Login_tmp_stream << "                    <div class=\"col\">\n";
	Login_tmp_stream << "                      <div class=\"form-outline form-white\">\n";
	Login_tmp_stream << "                        <input type=\"password\" id=\"typePasswordX\" name=\"password\" class=\"form-control form-control-lg\" />\n";
	Login_tmp_stream << "                        <label class=\"form-label text-start\" for=\"typePasswordX\">密码</label>\n";
	Login_tmp_stream << "                      </div>\n";
	Login_tmp_stream << "                    </div>\n";
	Login_tmp_stream << "                  </div>\n";
	Login_tmp_stream << "                  <p class=\"small mb-5 pb-lg-2\">\n";
	Login_tmp_stream << "                    <a class=\"text-white-50\" href=\"#!\">忘记密码</a>\n";
	Login_tmp_stream << "                  </p>\n";
	Login_tmp_stream << "                  <button class=\"btn btn-outline-light btn-lg px-5\" type=\"submit\">登录</button>\n";
	Login_tmp_stream << "                </div>\n";
	Login_tmp_stream << "                </form>\n";
	Login_tmp_stream << "              </div>\n";
	Login_tmp_stream << "            </div>\n";
	Login_tmp_stream << "          </div>\n";
	Login_tmp_stream << "        </div>\n";
	Login_tmp_stream << "      </div>\n";
	Login_tmp_stream << "    </section>\n";
	Login_tmp_stream << "  </body>\n";
Login_tmp_stream<<"\n";
	Login_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(Login_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Login_view_data;
auto str = std::move(Login_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
