//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Login:public drogon::DrTemplate<Login>
{
public:
	Login(){};
	virtual ~Login(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
