//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Sidebar:public drogon::DrTemplate<Sidebar>
{
public:
	Sidebar(){};
	virtual ~Sidebar(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
