/**
 *
 *  Invoiceline.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace sqlite3
{

class Invoiceline
{
  public:
    struct Cols
    {
        static const std::string _InvoiceLineId;
        static const std::string _InvoiceId;
        static const std::string _TrackId;
        static const std::string _UnitPrice;
        static const std::string _Quantity;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = uint64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Invoiceline(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Invoiceline(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Invoiceline(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Invoiceline() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column InvoiceLineId  */
    ///Get the value of the column InvoiceLineId, returns the default value if the column is null
    const uint64_t &getValueOfInvoicelineid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getInvoicelineid() const noexcept;
    ///Set the value of the column InvoiceLineId
    void setInvoicelineid(const uint64_t &pInvoicelineid) noexcept;

    /**  For column InvoiceId  */
    ///Get the value of the column InvoiceId, returns the default value if the column is null
    const uint64_t &getValueOfInvoiceid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getInvoiceid() const noexcept;
    ///Set the value of the column InvoiceId
    void setInvoiceid(const uint64_t &pInvoiceid) noexcept;

    /**  For column TrackId  */
    ///Get the value of the column TrackId, returns the default value if the column is null
    const uint64_t &getValueOfTrackid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getTrackid() const noexcept;
    ///Set the value of the column TrackId
    void setTrackid(const uint64_t &pTrackid) noexcept;

    /**  For column UnitPrice  */
    ///Get the value of the column UnitPrice, returns the default value if the column is null
    const std::string &getValueOfUnitprice() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUnitprice() const noexcept;
    ///Set the value of the column UnitPrice
    void setUnitprice(const std::string &pUnitprice) noexcept;
    void setUnitprice(std::string &&pUnitprice) noexcept;

    /**  For column Quantity  */
    ///Get the value of the column Quantity, returns the default value if the column is null
    const uint64_t &getValueOfQuantity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getQuantity() const noexcept;
    ///Set the value of the column Quantity
    void setQuantity(const uint64_t &pQuantity) noexcept;


    static size_t getColumnNumber() noexcept {  return 5;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Invoiceline>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Invoiceline>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint64_t> invoicelineid_;
    std::shared_ptr<uint64_t> invoiceid_;
    std::shared_ptr<uint64_t> trackid_;
    std::shared_ptr<std::string> unitprice_;
    std::shared_ptr<uint64_t> quantity_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[5]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where InvoiceLineId = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where InvoiceLineId = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[1])
        {
            sql += "InvoiceId,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "TrackId,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "UnitPrice,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "Quantity,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace sqlite3
} // namespace drogon_model
