/**
 *
 *  Invoice.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace sqlite3
{

class Invoice
{
  public:
    struct Cols
    {
        static const std::string _InvoiceId;
        static const std::string _CustomerId;
        static const std::string _InvoiceDate;
        static const std::string _BillingAddress;
        static const std::string _BillingCity;
        static const std::string _BillingState;
        static const std::string _BillingCountry;
        static const std::string _BillingPostalCode;
        static const std::string _Total;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = uint64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Invoice(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Invoice(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Invoice(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Invoice() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column InvoiceId  */
    ///Get the value of the column InvoiceId, returns the default value if the column is null
    const uint64_t &getValueOfInvoiceid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getInvoiceid() const noexcept;
    ///Set the value of the column InvoiceId
    void setInvoiceid(const uint64_t &pInvoiceid) noexcept;

    /**  For column CustomerId  */
    ///Get the value of the column CustomerId, returns the default value if the column is null
    const uint64_t &getValueOfCustomerid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getCustomerid() const noexcept;
    ///Set the value of the column CustomerId
    void setCustomerid(const uint64_t &pCustomerid) noexcept;

    /**  For column InvoiceDate  */
    ///Get the value of the column InvoiceDate, returns the default value if the column is null
    const ::trantor::Date &getValueOfInvoicedate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getInvoicedate() const noexcept;
    ///Set the value of the column InvoiceDate
    void setInvoicedate(const ::trantor::Date &pInvoicedate) noexcept;

    /**  For column BillingAddress  */
    ///Get the value of the column BillingAddress, returns the default value if the column is null
    const std::string &getValueOfBillingaddress() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBillingaddress() const noexcept;
    ///Set the value of the column BillingAddress
    void setBillingaddress(const std::string &pBillingaddress) noexcept;
    void setBillingaddress(std::string &&pBillingaddress) noexcept;
    void setBillingaddressToNull() noexcept;

    /**  For column BillingCity  */
    ///Get the value of the column BillingCity, returns the default value if the column is null
    const std::string &getValueOfBillingcity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBillingcity() const noexcept;
    ///Set the value of the column BillingCity
    void setBillingcity(const std::string &pBillingcity) noexcept;
    void setBillingcity(std::string &&pBillingcity) noexcept;
    void setBillingcityToNull() noexcept;

    /**  For column BillingState  */
    ///Get the value of the column BillingState, returns the default value if the column is null
    const std::string &getValueOfBillingstate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBillingstate() const noexcept;
    ///Set the value of the column BillingState
    void setBillingstate(const std::string &pBillingstate) noexcept;
    void setBillingstate(std::string &&pBillingstate) noexcept;
    void setBillingstateToNull() noexcept;

    /**  For column BillingCountry  */
    ///Get the value of the column BillingCountry, returns the default value if the column is null
    const std::string &getValueOfBillingcountry() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBillingcountry() const noexcept;
    ///Set the value of the column BillingCountry
    void setBillingcountry(const std::string &pBillingcountry) noexcept;
    void setBillingcountry(std::string &&pBillingcountry) noexcept;
    void setBillingcountryToNull() noexcept;

    /**  For column BillingPostalCode  */
    ///Get the value of the column BillingPostalCode, returns the default value if the column is null
    const std::string &getValueOfBillingpostalcode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBillingpostalcode() const noexcept;
    ///Set the value of the column BillingPostalCode
    void setBillingpostalcode(const std::string &pBillingpostalcode) noexcept;
    void setBillingpostalcode(std::string &&pBillingpostalcode) noexcept;
    void setBillingpostalcodeToNull() noexcept;

    /**  For column Total  */
    ///Get the value of the column Total, returns the default value if the column is null
    const std::string &getValueOfTotal() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTotal() const noexcept;
    ///Set the value of the column Total
    void setTotal(const std::string &pTotal) noexcept;
    void setTotal(std::string &&pTotal) noexcept;


    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Invoice>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Invoice>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint64_t> invoiceid_;
    std::shared_ptr<uint64_t> customerid_;
    std::shared_ptr<::trantor::Date> invoicedate_;
    std::shared_ptr<std::string> billingaddress_;
    std::shared_ptr<std::string> billingcity_;
    std::shared_ptr<std::string> billingstate_;
    std::shared_ptr<std::string> billingcountry_;
    std::shared_ptr<std::string> billingpostalcode_;
    std::shared_ptr<std::string> total_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where InvoiceId = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where InvoiceId = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[1])
        {
            sql += "CustomerId,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "InvoiceDate,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "BillingAddress,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "BillingCity,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "BillingState,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "BillingCountry,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "BillingPostalCode,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "Total,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace sqlite3
} // namespace drogon_model
