/**
 *
 *  Mediatype.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Mediatype.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Mediatype::Cols::_MediaTypeId = "MediaTypeId";
const std::string Mediatype::Cols::_Name = "Name";
const std::string Mediatype::primaryKeyName = "MediaTypeId";
const bool Mediatype::hasPrimaryKey = true;
const std::string Mediatype::tableName = "mediatype";

const std::vector<typename Mediatype::MetaData> Mediatype::metaData_={
{"MediaTypeId","uint64_t","integer",8,1,1,1},
{"Name","std::string","nvarchar(120)",0,0,0,0}
};
const std::string &Mediatype::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Mediatype::Mediatype(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["MediaTypeId"].isNull())
        {
            mediatypeid_=std::make_shared<uint64_t>(r["MediaTypeId"].as<uint64_t>());
        }
        if(!r["Name"].isNull())
        {
            name_=std::make_shared<std::string>(r["Name"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            mediatypeid_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Mediatype::Mediatype(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            mediatypeid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

Mediatype::Mediatype(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("MediaTypeId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["MediaTypeId"].isNull())
        {
            mediatypeid_=std::make_shared<uint64_t>((uint64_t)pJson["MediaTypeId"].asUInt64());
        }
    }
    if(pJson.isMember("Name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["Name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["Name"].asString());
        }
    }
}

void Mediatype::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            mediatypeid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void Mediatype::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("MediaTypeId"))
    {
        if(!pJson["MediaTypeId"].isNull())
        {
            mediatypeid_=std::make_shared<uint64_t>((uint64_t)pJson["MediaTypeId"].asUInt64());
        }
    }
    if(pJson.isMember("Name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["Name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["Name"].asString());
        }
    }
}

const uint64_t &Mediatype::getValueOfMediatypeid() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(mediatypeid_)
        return *mediatypeid_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Mediatype::getMediatypeid() const noexcept
{
    return mediatypeid_;
}
void Mediatype::setMediatypeid(const uint64_t &pMediatypeid) noexcept
{
    mediatypeid_ = std::make_shared<uint64_t>(pMediatypeid);
    dirtyFlag_[0] = true;
}
const typename Mediatype::PrimaryKeyType & Mediatype::getPrimaryKey() const
{
    assert(mediatypeid_);
    return *mediatypeid_;
}

const std::string &Mediatype::getValueOfName() const noexcept
{
    const static std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Mediatype::getName() const noexcept
{
    return name_;
}
void Mediatype::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Mediatype::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}
void Mediatype::setNameToNull() noexcept
{
    name_.reset();
    dirtyFlag_[1] = true;
}

void Mediatype::updateId(const uint64_t id)
{
    mediatypeid_ = std::make_shared<uint64_t>(id);
}

const std::vector<std::string> &Mediatype::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "Name"
    };
    return inCols;
}

void Mediatype::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Mediatype::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Mediatype::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Mediatype::toJson() const
{
    Json::Value ret;
    if(getMediatypeid())
    {
        ret["MediaTypeId"]=(Json::UInt64)getValueOfMediatypeid();
    }
    else
    {
        ret["MediaTypeId"]=Json::Value();
    }
    if(getName())
    {
        ret["Name"]=getValueOfName();
    }
    else
    {
        ret["Name"]=Json::Value();
    }
    return ret;
}

Json::Value Mediatype::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getMediatypeid())
            {
                ret[pMasqueradingVector[0]]=(Json::UInt64)getValueOfMediatypeid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getMediatypeid())
    {
        ret["MediaTypeId"]=(Json::UInt64)getValueOfMediatypeid();
    }
    else
    {
        ret["MediaTypeId"]=Json::Value();
    }
    if(getName())
    {
        ret["Name"]=getValueOfName();
    }
    else
    {
        ret["Name"]=Json::Value();
    }
    return ret;
}

bool Mediatype::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("MediaTypeId"))
    {
        if(!validJsonOfField(0, "MediaTypeId", pJson["MediaTypeId"], err, true))
            return false;
    }
    if(pJson.isMember("Name"))
    {
        if(!validJsonOfField(1, "Name", pJson["Name"], err, true))
            return false;
    }
    return true;
}
bool Mediatype::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Mediatype::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("MediaTypeId"))
    {
        if(!validJsonOfField(0, "MediaTypeId", pJson["MediaTypeId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("Name"))
    {
        if(!validJsonOfField(1, "Name", pJson["Name"], err, false))
            return false;
    }
    return true;
}
bool Mediatype::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Mediatype::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
